pub mod api;

use std::{
    env,
    ffi::{c_int, CStr},
    os::raw::c_char,
};

const BAMBU_NETWORK_SUCCESS: i32 = 0;
const BAMBU_NETWORK_ERR_INVALID_HANDLE: i32 = -1;
const BAMBU_NETWORK_ERR_CONNECT_FAILED: i32 = -2;
const BAMBU_NETWORK_ERR_DISCONNECT_FAILED: i32 = -3;
const BAMBU_NETWORK_ERR_SEND_MSG_FAILED: i32 = -4;
const BAMBU_NETWORK_ERR_BIND_FAILED: i32 = -5;
const BAMBU_NETWORK_ERR_UNBIND_FAILED: i32 = -6;
const BAMBU_NETWORK_ERR_REQUEST_SETTING_FAILED: i32 = -7;
const BAMBU_NETWORK_ERR_PUT_SETTING_FAILED: i32 = -8;
const BAMBU_NETWORK_ERR_GET_SETTING_LIST_FAILED: i32 = -9;
const BAMBU_NETWORK_ERR_DEL_SETTING_FAILED: i32 = -10;
const BAMBU_NETWORK_ERR_GET_USER_PRINTINFO_FAILED: i32 = -11;
const BAMBU_NETWORK_ERR_QUERY_BIND_INFO_FAILED: i32 = -12;
const BAMBU_NETWORK_ERR_MODIFY_PRINTER_NAME_FAILED: i32 = -13;
const BAMBU_NETWORK_ERR_FILE_NOT_EXIST: i32 = -14;
const BAMBU_NETWORK_ERR_FILE_OVER_SIZE: i32 = -15;
const BAMBU_NETWORK_ERR_CHECK_MD5_FAILED: i32 = -16;
const BAMBU_NETWORK_ERR_TIMEOUT: i32 = -17;
const BAMBU_NETWORK_ERR_CANCELED: i32 = -18;
const BAMBU_NETWORK_ERR_INVALID_RESULT: i32 = -19;
const BAMBU_NETWORK_ERR_FTP_UPLOAD_FAILED: i32 = -20;
